trigger:
  branches:
    include:
      - main

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals kmaster

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'prmd77/frontend'
  containerRegistry: 'prmd77'
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: 'aks-service-connection'
  namespace: 'default'

stages:
  - stage: Build
    displayName: Build and Push
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: Build and Push image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: '**/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: |
                apex-front-main/k8s/deployment.yaml
                apex-front-main/k8s/service.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
