trigger:
  branches:
    include:
      - none  # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'prmd77/frontend'
  containerRegistry: 'prmd77'
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: 'aks-service-connection'
  namespace: 'default'
  dockerUsername: 'prmd77'       # direct value
 

stages:
  - stage: Build
    displayName: Build, Scan & Push
    jobs:
      - job: BuildandScan
        displayName: Build and Scan
        steps:
          - checkout: self

          # ✅ SonarCloud Prepare
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarqubeServiceConnection'
              organization: 'cloudsolution'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'cloudsolution_cloudsolution'
              cliProjectName: 'cloudsolution'
              extraProperties: |
                sonar.sources=.
                sonar.exclusions=**/tests/**

          # ✅ Run SonarCloud Analysis
          - task: SonarCloudAnalyze@1

          # ✅ TFLint install and run
          - script: |
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint
            displayName: "Run TFLint"

          # ✅ Checkov install and run
          - script: |
              pip install checkov
              checkov -d .
            displayName: "Run Checkov"

          # ✅ tfsec run
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              debug: true
              dir: 'apex-front-main'

          # ✅ Docker build + push temp image for Trivy scan
          - task: Docker@2
            displayName: Build & Push Temp Image for Scan
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: '**/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest

          # ✅ Install Trivy on Hosted Agent
          - script: |
              sudo apt-get update -y
              sudo apt-get install -y wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
              echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
              sudo apt-get update -y
              sudo apt-get install -y trivy
              trivy --version
            displayName: "Install Trivy"

          # ✅ Validate Docker credentials
          - script: |
              if [ -z "$(dockerUsername)" ] || [ -z "$(dockerPasswordSecret)" ]; then
                echo "Error: Docker credentials are not set properly!"
                exit 1
              fi
            displayName: "Validate Docker Credentials"

          # ✅ Trivy remote scan using Docker Hub credentials
          - script: |
              echo "Scanning remote image with Trivy..."
              trivy image \
                --exit-code 0 \
                --severity HIGH,CRITICAL \
                --username $(dockerUsername) \
                --password $(dockerPasswordSecret) \
                $(imageRepository):temp-scan
            displayName: "Trivy Remote Scan"

          # ✅ Push final image only if scan passes
          - task: Docker@2
            displayName: Push Final Image
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: [Build]
    jobs:
      - job: Deploy
        steps:
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: |
                apex-front-main/frontend-deployment.yaml
                apex-front-main/service.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
            continueOnError: true
