trigger:
 branches:
   include:
     - main


  variables:
  dockerRegistryServiceConnection: 'dockerhub-service-connection'
  imageRepository: 'frontend'
  containerRegistry: '<your-dockerhub-username>'
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: 'aks-service-connection'
  namespace: 'default'

  stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '**/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: KubernetesManifest@1
      displayName: Deploy to AKS
      inputs:
        action: deploy
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        namespace: $(namespace)
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        containers: |
          $(containerRegistry)/$(imageRepository):$(tag)