trigger:
  branches:
    include:
      - none

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals kmaster

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'prmd77/frontend'
  containerRegistry: 'prmd77'
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: 'aks-service-connection'
  namespace: 'default'

stages:
  - stage: Build
    displayName: Build and Push
    jobs:
      - job: Build
        displayName: build and scan
        steps:
          - checkout: self
         # TFLint install and run
        - script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            tflint
          displayName: "Run TFLint"

        # Checkov install and run
        - script: |
            pip install checkov
            checkov -d .
          displayName: "Run Checkov"
        
        # tfsec install and run
        



        - task: Docker@2
           displayName: Build and Push image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: '**/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - job: Deploy
        
        steps:
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: |                
                  apex-front-main/frontend-deployment.yaml
                  apex-front-main/service.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
