trigger:
  branches:
    include:
      - none  # Manual trigger only

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals awshosted

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'prmd77/frontend'
  containerRegistry: 'prmd77'
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: 'aks-service-connection'
  namespace: 'default'

stages:
  - stage: Build
    displayName: Build and Push
    jobs:
      - job: BuildandScan
        displayName: Build and Scan
        steps:
          - checkout: self

          # SonarCloud Prepare
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarqubeServiceConnection'    # Replace with your service connection name
              organization: 'cloudsolution'               # From SonarCloud URL
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'cloudsolution_cloudsolution'
              cliProjectName: 'cloudsolution'
              extraProperties: |
                sonar.sources=.
                sonar.exclusions=**/tests/**

          #  TFLint install and run
          - script: |
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint
            displayName: "Run TFLint"

          # Checkov install and run
          - script: |
              pip install checkov
              checkov -d .
            displayName: "Run Checkov"

          # tfsec run
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              debug: true
              dir: 'apex-front-main'

          #  SonarCloud Analyze
          - task: SonarCloudAnalyze@1

          # Docker build and push
          - task: Docker@2
            displayName: Build and Push image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: '**/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

          # SonarCloud Publish
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'

  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - job: Deploy
        steps:
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: |                
                apex-front-main/frontend-deployment.yaml
                apex-front-main/service.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
