trigger:
  branches:
    include:
      - none  # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'prmd77/frontend'
  containerRegistry: 'prmd77'
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: 'aks-service-connection'
  namespace: 'frontend-ns'
  dockerUsername: 'prmd77'       # direct value
 

stages:
  - stage: Build
    displayName: Build, Scan & Push
    jobs:
      - job: BuildandScan
        displayName: Build and Scan
        steps:
          - checkout: self

          # SonarCloud Prepare
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarqubeServiceConnection'
              organization: 'cloudsolution'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'cloudsolution_cloudsolution'
              cliProjectName: 'cloudsolution'
              extraProperties: |
                sonar.sources=.
                sonar.exclusions=**/tests/**

          # SonarCloud Analyze
          - task: SonarCloudAnalyze@1

          # TFLint
          - script: |
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint
            displayName: "Run TFLint"

          # Checkov
          - script: |
              pip install checkov
              checkov -d .
            displayName: "Run Checkov"

          # tfsec
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              debug: true
              dir: 'apex-front-main'

          # Docker Build & Push Temp Image for Scan
          - task: Docker@2
            displayName: Build & Push Temp Image for Scan
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: '**/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                temp-scan

          # Install Trivy
          - script: |
              sudo apt-get update -y
              sudo apt-get install -y wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
              echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
              sudo apt-get update -y
              sudo apt-get install -y trivy
              trivy --version
            displayName: "Install Trivy"

          # Validate Docker Credentials
          - script: |
              if [ -z "$(dockerUsername)" ] || [ -z "$(dockerPasswordSecret)" ]; then
                echo "Error: Docker credentials are not set properly!"
                exit 1
              fi
            displayName: "Validate Docker Credentials"

          # Trivy Scan on temp-scan image
          - script: |
              echo "Scanning remote image with Trivy..."
              trivy image \
                --exit-code 1 \
                --severity HIGH,CRITICAL \
                --username $(dockerUsername) \
                --password $(dockerPasswordSecret) \
                $(imageRepository):temp-scan
            displayName: "Trivy Remote Scan"

          # Build Final Image (with $(tag))
          - task: Docker@2
            displayName: Build Final Image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: '**/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

          # Push Final Image
          - task: Docker@2
            displayName: Push Final Image
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
  

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: [Build]
    jobs:
      - job: Deploy
        steps:
        - task: Kubernetes@1
          displayName: "Apply RBAC Role and RoleBinding"
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: $(kubernetesServiceConnection)
            command: apply
            useConfigurationFile: true
            configuration: 'apex-front-main/rbac.yaml'
            arguments: --validate=false
            namespace: $(namespace)

        - task: KubernetesManifest@1
          displayName: Deploy to AKS
          inputs:
            action: deploy
            kubernetesServiceConnection: 'aks-service-connection'
            namespace: $(namespace)
            manifests: |
              apex-front-main/frontend-deployment.yaml
              apex-front-main/service.yaml
            containers: |
              $(containerRegistry)/$(imageRepository):$(tag)
          continueOnError: true



