# checkov:skip=CKV_K8S_43: Using tag instead of digest for dev environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: deployment-sa    # <-- yaha add kiya service account name
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 30001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: prmd77/frontend:430
 # replace with actual digest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
          - name: REACT_APP_API_URL
            value: "http://backend-service:5000"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 30001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
