apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa         # service account ka naam
  namespace: frontend-ns       # ye wahi namespace hona chahiye jaha deployment hoga

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: frontend-ns       # wohi namespace jisme deploy kar rahe ho
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: frontend-ns
subjects:
- kind: ServiceAccount
  name: deployment-sa         # wahi service account jo upar banaya
  namespace: frontend-ns      # same namespace
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
